name: Notification To Team

on:
  pull_request:
    types:
      - closed
    branches:
      - production

jobs:
  linear-integration:
    name: linear Integration
    runs-on: ubuntu-latest
    steps:
      - name: print latest commit message
        run: |
          set -e
          
          echo "test"
