name: Comment Build Dev Done on Linear

on:
  push:
    branches:
      - main

jobs:
  linear-integration:
    name: linear Integration
    runs-on: ubuntu-latest
    steps:
      - name: print latest commit message
        env:
          LAST_COMMIT_MESSAGE: "D1-1700"
        run: |
          echo "last commit message: $LAST_COMMIT_MESSAGE"
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.workflow_run.head_commit.message }}
          regex: '^.+(D1-[0-9]+).*$'
          flags: gm
      - name: linear issue comment

        env:
          LINEAR_ISSUE_ID: "D1-1700"
          LINEAR_API_TOKEN: ${{ secrets.LINEAR_BOT_TOKEN }}
        run: |
          set -e

          query='{"query":"query Me { issue(id: \"'$LINEAR_ISSUE_ID'\") { assignee { id displayName } } }"}'

          headers='{"Content-Type": "application/json", "Authorization": "Bearer '$LINEAR_API_TOKEN'"}'

          response=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: $LINEAR_API_TOKEN" \
            -d "$query" \
            https://api.linear.app/graphql)

          assignee_id=$(echo "$response" | jq -r '.data.issue.assignee.id')
          assignee_display_name=$(echo "$response" | jq -r '.data.issue.assignee.displayName')

          echo "Assignee ID 1: $assignee_id"
          echo "Assignee Name 1: $assignee_display_name"
          
          echo "Assignee ID 1: $assignee_id"
          echo "Assignee Name 1: $assignee_display_name"
          echo "linear issue id: $LINEAR_ISSUE_ID"

          query='{"query": "mutation test { commentCreate(input: { issueId: \"'$LINEAR_ISSUE_ID'\", bodyData: { type: \"doc\", content: [ { type: \"paragraph\", content: [ { type: \"text\", text: \"Hi \" }, { type: \"suggestion_userMentions\", attrs: { id: \"'$assignee_id'\", label: \"'$assignee_display_name'\" } }, { type: \"text\", text: \" \" }, { type: \"text\", text: \"code built to Develop\" } ] } ] } ) { success } }"}'
          
          headers='{"Content-Type": "application/json", "Authorization": "Bearer '$LINEAR_API_TOKEN'"}'

          response=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: $LINEAR_API_TOKEN" \
            -d "$query" \
            https://api.linear.app/graphql)
          
          errors=$(echo "$response" | jq -r '.errors')
          
          if [ -n "$errors" ]; then
            echo "GraphQL errors: $errors"
          else
            success=$(echo "$response" | jq -r '.data.commentCreate.success')
            
            if [ "$success" == "true" ]; then
              echo "Comment created successfully."
            else
              echo "Failed to create comment."
            fi
          fi
