name: Comment Build Dev Done on Linear

on:
  workflow_run:
    workflows:
      - CRM Frontend CI
    types:
      - completed
  pull_request:
    types:
      - closed
    branches:
      - production

jobs:
  linear-integration:
    name: linear Integration
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: print latest commit message
        env:
          LAST_COMMIT_MESSAGE: ${{ github.event.workflow_run.head_commit.message }}
        run: |
          echo "last commit message: $LAST_COMMIT_MESSAGE"
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.workflow_run.head_commit.message }}
          regex: '^.+(D1-[0-9]+).*$'
          flags: gm
      - name: linear issue comment
        if: ${{ steps.regex-match.outputs.match != '' }}
        env:
          LINEAR_ISSUE_ID: ${{ steps.regex-match.outputs.group1 }}
          LINEAR_API_TOKEN: ${{ secrets.LINEAR_BOT_TOKEN }}
        run: |
          set -e
          
          echo 'test'
