name: Notification To Team

on:
  workflow_run:
    workflows:
      - CRM Frontend CI
    types:
      - completed
  pull_request:
    types:
      - closed
    branches:
      - production

jobs:
  linear-integration:
    name: linear Integration
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: print latest commit message
        run: |
          set -e
          
          echo 'test'
          echo 'test'
          echo 'test'
          echo 'test'
          echo 'test'
